### ISSUE TITLE
Specify col_types

### ISSUE THREAD

**Issue by R3myG** [jimhester/vroom#12]
Thanks for the great work Jim! 
It would be great if vroom could take the col_types argument just like readr so that in configurations like below wouldn't result in a wrong column type. 

For the files I read, vroom is 5 times faster than readr but because a lot of columns types are wrong, I lose all the benefits when correcting it. And no, I can't get rid of those missing values in some of my columns :( 

In this example, having an NA value on the first row will result in the col type to change from dbl to chr. 

``` r
mtcarsBis <- mtcars
mtcarsBis$vs[1] <- NA
readr::write_tsv(mtcarsBis, "mtcars.tsv")
mtcarsBack <- vroom::vroom("mtcars.tsv")
dplyr::glimpse(mtcars)
#> Observations: 32
#> Variables: 11
#> $ mpg  <dbl> 21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19....
#> $ cyl  <dbl> 6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, ...
#> $ disp <dbl> 160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 360.0, 146.7, 1...
#> $ hp   <dbl> 110, 110, 93, 110, 175, 105, 245, 62, 95, 123, 123, 180, ...
#> $ drat <dbl> 3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3.69, 3.92, 3.9...
#> $ wt   <dbl> 2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3.570, 3.190, 3...
#> $ qsec <dbl> 16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.00, 2...
#> $ vs   <dbl> 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, ...
#> $ am   <dbl> 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...
#> $ gear <dbl> 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, ...
#> $ carb <dbl> 4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, ...
dplyr::glimpse(mtcarsBack)
#> Observations: 32
#> Variables: 11
#> $ mpg  <dbl> 21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19....
#> $ cyl  <int> 6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, ...
#> $ disp <dbl> 160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 360.0, 146.7, 1...
#> $ hp   <int> 110, 110, 93, 110, 175, 105, 245, 62, 95, 123, 123, 180, ...
#> $ drat <dbl> 3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3.69, 3.92, 3.9...
#> $ wt   <dbl> 2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3.570, 3.190, 3...
#> $ qsec <dbl> 16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.00, 2...
#> $ vs   <chr> "NA", "0", "1", "1", "0", "1", "0", "1", "1", "1", "1", "...
#> $ am   <int> 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...
#> $ gear <int> 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, ...
#> $ carb <int> 4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, ...
```

**Comment by jimhester** [comment]
Oh, yeah missing values are not currently being handled yet, it is in the todo, #8

**Comment by R3myG** [comment]
I don't know exactly how currently vroom decides on the col type (I will assume by looking at the first value?) but if vroom knew exactly which col type to use for each column, this could speed it up and address most of the missing value problems?

**Comment by R3myG** [comment]
Awesome! Thanks a lot! 
I tried on a file which has on a few columns with a lot of NAs before getting into numbers and vroom still gets tricked (although it detects them as lgl instead of chr) but I don't expect any function to automatically go around that without taking a massive toll on the speed. 
Looking forward to the implementation of `col_types`!

**Comment by jimhester** [comment]
It only currently only uses the first 100 rows to determine the column type, so if they are all missing it will be guessed as logical.

**Comment by R3myG** [comment]
Sounds fair! As I said, this is a particular case I have and I don't expect vroom or readr or any other function to address this issue.

**Comment by Evgeniy-** [comment]
Yes, please add column types. I've faced an issue when trying to vroom a folder of same-structured files: same column was sometimes guessed as numerics and other times as character. This gives an error when trying to bind_rows  (or when using map_df).
