### ISSUE TITLE
vroom_list to import from a vector of files?

### ISSUE THREAD

**Issue by Evgeniy-** [jimhester/vroom#17]
Please consider adding a function to import from a vector of file names. Similar to import_list from {rio}.
So e.g. whole folder of .csv files can be vroom'ed in single data frame without materializing the stuff. 
Great stuff overall! This brings the performance to the whole new level!

**Comment by jimhester** [comment]
I will keep it in mind, but it is going to be pretty tricky to implement, so is unlikely to be done in the near future.

**Comment by Evgeniy-** [comment]
Thanks! Do you have a toy example how to use purr::map() in this context to avoid materializing datasets when importing from the files?

**Comment by jimhester** [comment]
Thanks for the feature request!

This now should work, you can simply pass `vroom()` a vector of filenames to read them.

It has only been tested on a few files, so there are likely still bugs to be ironed out however.

**Comment by Evgeniy-** [comment]
Thank you!
