### ISSUE TITLE
fixed width files

### ISSUE THREAD

**Issue by jimhester** [jimhester/vroom#33]
- [x] basic reading
- [x] column types
- [x] column skips
- [x] locales
- [x] nas
- [x] trim_ws
- [x] guess_max
- [x] comment
- [x] header skip
- [x] n_max
- [x] num_threads (materializing)
- [x] ~num_threads (indexing) - maybe won't do~
- [x] progress
- [x] reading from connections
- [x] tests from readr

**Comment by jimhester** [comment]
This is now done, though we should probably add some tests for the connection code.

**Comment by GuillaumePressiat** [comment]
Hi,

A return;

Thank you very much for this vroom vroom !

I test it with my files (> 1,3 million lines and 130 columns).

I've made a little video :  
https://www.youtube.com/watch?v=UYAH2k8jEKk&feature=youtu.be&vq=720p60hd

The fact that you reassigned readr parameters is really a good point.

Many thanks

**Comment by jimhester** [comment]
Great, thanks!
