### ISSUE TITLE
.csv loads too slow to enviroment. 

### ISSUE THREAD

**Issue by telaroz** [jimhester/vroom#46]
I read a 2MO rows and 9 column .csv file (1.2 GB) and vroom reads it in around 4 seconds (vs 7.7 seconds for fread). But it takes around 1 minute to load to the RStudio enviroment (vs 2 seconds for fread). 

I´m using RStudio Version 1.2.1237 and R version 3.5.2.

**Comment by jimhester** [comment]
See https://github.com/jimhester/vroom#rstudio-caveats, you need to turn off the auto refresh for the environment or use the daily version of RStudio.
