### ISSUE TITLE
Using vroom with col_names crashes R

### ISSUE THREAD

**Issue by md0u80c9** [jimhester/vroom#56]
Hi,

Using a copy of 0.0.0.9000 fetched 2 hours ago.

I've been trying to do a selective column fetch from my CSV file.

If I fetch the whole file using:

`test <- vroom::vroom("../myfile.csv")
`

This works fine and fetches the whole CSV file.

I then tried to do the following with the intent of fetching just two columns:

`test2 <- vroom::vroom("../myfile.csv", col_names = c("CreatedDateTime", "CreatedUserName"))
`

which caused R to abort the session with a fatal error. Replicated the test - same error.

**Comment by md0u80c9** [comment]
I've realised that the error in my code is that col_names will be for fully specifying all column names, not just specifying which ones you want from a CSV file with named columns - so the code presumably fails to spot the mismatch between the length of the character vector and the CSV file which causes the fatal crash.


In a related question...

If you don't want to specify the column type - how do you selectively import columns, starting with just a character vector of column names? Do you use purrr to produce a col spec with each parameter being equal to col_guess()? Or is there a simpler method?

**Comment by jimhester** [comment]
You use the column type argument with a guessed type, the same as readr.

```r
test2 <- vroom::vroom("../myfile.csv", col_type = cols_only("CreatedDateTime" = "?", "CreatedUserName" = "?"))
```

**Comment by jimhester** [comment]
I am going to close this, I opened a different issue to track the crash.
