### ISSUE TITLE
Understanding vroom performance

### ISSUE THREAD

**Issue by md0u80c9** [jimhester/vroom#59]
Hi,

I've finally found some time to try replacing readr with vroom in my R package: whilst it is clearly working as intended understanding how it works differently to readr is obviously critical. I'm kind of asking questions here, but it may be a helpful issue to generate a vignette from in future.

I have a function, read_ssnap_csv that uses readr to load the CSV and then perform the tidying. I've duplicated it as read_audit_csv, and swapped out readr for vroom.

What I've discovered so far is that if I use vroom I get significant speed gains loading my R file. I took the functions and stopped the code after the file read operation:

This is vroom:
```
                                                      expr      min       lq     mean
 ssnapinterface::read_audit_csv("../SSNAPTestData316.csv") 61.48958 70.04886 110.3929
   median       uq      max neval
 96.73592 110.6406 294.9985    10

```

This is readr:
```
Unit: milliseconds
                                                               expr      min       lq
 ssnapinterface::read_ssnap_csv("../SSNAPTestData316.csv", "3.1.6") 125.0023 127.4047
     mean   median       uq      max neval
 169.9288 137.0685 216.3664 273.7023    10

```

However, the functions then undertake some tidying of the data using a set of dplyr functions (mutate, filter, etc).

After tidying, we lose all that advantage and vroom ends up much slower than readr:

Vroom:
```
                                                      expr     min       lq     mean
 ssnapinterface::read_audit_csv("../SSNAPTestData316.csv") 535.522 546.9812 585.3708
   median       uq      max neval
 554.6229 569.3828 829.7836    10

```

Readr:
```
Unit: milliseconds
                                                               expr      min       lq
 ssnapinterface::read_ssnap_csv("../SSNAPTestData316.csv", "3.1.6") 308.5204 327.5631
     mean   median       uq      max neval
 375.7263 353.3448 412.5121 520.2157    10

```

So clearly the type and usage of functions to process vroom data is really important. Are there ways to tidy the data which are more 'vroom-friendly'? Any obvious dos and don'ts based upon how vroom works which might explain this big difference?

**Comment by md0u80c9** [comment]
Just managed to understand this further by walking through both files and benchmarking subsequent statements.

The thing that makes the difference is this:

```
    imported_data <- dplyr::filter(
      imported_data,
      dplyr::between(.data[["TeamCode"]], -900, 900))

```

This adds 3ms onto the readr code; but adds 270ms onto the vroom code using the CRAN version of dplyr 0.8.0.1.

**Comment by md0u80c9** [comment]
From the above, I've just tried switching the order of our tidy operations. Rather than do the filter operation first, I've moved a subsequent mutate_at first.

Again - readr becomes faster than vroom as soon as we do the mutate_at. This takes 130ms on the vroom version of the function as opposed to 28ms for the readr version.

**Comment by jimhester** [comment]
This is mentioned in the [benchmarking vignette](https://jimhester.github.io/vroom/articles/benchmarks.html)

> (N.B. currently the dplyr implementation materializes the all numeric vectors when using filter() or sample_n(), so these cases are not as fast as they could otherwise be).

But in addition there seem to be other issues with the way dplyr is accessing the data in group_by and elsewhere that make it slow, improving this is what I am working on now.

In the meantime if you run `vroom:::vroom_materialize()` after running vroom it will fully materialize all the vectors and the performance for other manipulations will then be equivalent to normal R vectors.

It would be useful for me to see the code and data you are using to test, so I can work to make sure the performance improves in your use case.

**Comment by md0u80c9** [comment]
Yeah - I'd read the benchmarking vignette: this was partly why I was trying to check whether it was something to do with the way I was using the data after loading it, or whether it was something about the way dplyr makes assumptions about data, etc. I hadn't assumed by 'not as fast as they could otherwise be' that this could include 'much slower than readr' in similar scenarios - hence the query.

OK - the interface code is on a private repository - I've sent an invite to you for it (it will hopefully be fully open sourced shortly - working my way through red tape to make that happen!) I'll also send you access to the stats code it interfaces to (ideally my plan is for the stats engine to take both snapshots of data from CSV, or talk directly to an SQLServer database using dbplyr). Comments / feedback welcomed too.

The function you need is read_audit_csv (in read_csv.R) which does the CSV load and then a set of tidy ups. Key thing about the code is it's designed around permitting selective loading (and then tidying) of the datafile - so if you don't need all the data, you only load preselected columns. The older readr version is in read_ssnap_csv.R - there are some minor UI tidy ups going on between the two (dropping deprecated parameters etc); but nothing that will impact on performance significantly.

Do you have an email address to send you some fake data to use with it? You'll need to duplicate the fakes to make data at sufficient scale (real-life use cases involve a few thousand rows to 1M rows depending upon the type of analysis involved).

**Comment by jimhester** [comment]
Using some larger versions of the data you sent me, the latest version of vroom and https://github.com/tidyverse/dplyr/commit/4568fc176150c214ffb0d92274d3b46a864523cd I now get the following performance for this dataset.

```r
# Ran previously to make the input bigger (it is now 359,000 lines).
# t1 <- readr::read_lines("SSNAP_Export_fake only.csv")
# lines <- t1[-1]
# lines2 <- rep(lines, 1000)
# readr::write_lines(c(t1[[1]], lines2), "out.csv")

# With readr
system.time(read_ssnap_csv("out.csv", "3.1.6"))
#>   user  system elapsed
#>   7.014   0.556   7.577

# With vroom
system.time(read_ssnap_csv("out.csv", "3.1.6"))
#>    user  system elapsed
#>  13.982   0.539   6.486
```

It is possible there are more performance improvements to come, I will continue to investigate it.

**Comment by md0u80c9** [comment]
Awesome! I'll fetch the latest dplyr and test this (and the import from the other thread) this evening hopefully!

**Comment by md0u80c9** [comment]
Wow - just checked against the 'real' dataset - old function (read_ssnap_csv which uses readr) versus new function (read_audit_csv which uses vroom).

There is a massive gain in performance now using the real dataset (around 150% faster using vroom than using readr).

**Comment by jimhester** [comment]
Good to hear! I will close this for now then.
