### ISSUE TITLE
the `id` argument failed when dealing with compressed files

### ISSUE THREAD

**Issue by ginolhac** [jimhester/vroom#60]
Hey,

what a wonderful package, the few tests I did are much impressive, thanks a lot for your work. Also a big fan of your packages anyway ;)

I think I found a bug, using the great argument `id = "file"` but on compressed files.

``` r
library("magrittr")
purrr::iwalk(
 split(mtcars, mtcars$cyl), 
 ~ readr::write_tsv(.x, glue::glue("mtcars_{.y}.tsv.gz"))
)
fs::dir_ls(glob = "*tsv.gz") %>% vroom::vroom(id = "file")
#> Error in vroom_(file, delim = delim, col_names = col_names, col_types = col_types, : Expecting a single string value: [type=integer; extent=1].
```

<sup>Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

(using latest commit SHA1 (149d4794))

- if I write uncompressed files: all good
- if I don't use the `id` argument: all good.

``` r
library("magrittr")
purrr::iwalk(
 split(mtcars, mtcars$cyl), 
 ~ readr::write_tsv(.x, glue::glue("mtcars_{.y}.tsv.gz"))
)
fs::dir_ls(glob = "*tsv.gz") %>% vroom::vroom()
#> # A tibble: 32 x 11
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  22.8     4 108      93  3.85  2.32  18.6     1     1     4     1
#>  2  24.4     4 147.     62  3.69  3.19  20       1     0     4     2
#>  3  22.8     4 141.     95  3.92  3.15  22.9     1     0     4     2
#>  4  32.4     4  78.7    66  4.08  2.2   19.5     1     1     4     1
#>  5  30.4     4  75.7    52  4.93  1.62  18.5     1     1     4     2
#>  6  33.9     4  71.1    65  4.22  1.84  19.9     1     1     4     1
#>  7  21.5     4 120.     97  3.7   2.46  20.0     1     0     3     1
#>  8  27.3     4  79      66  4.08  1.94  18.9     1     1     4     1
#>  9  26       4 120.     91  4.43  2.14  16.7     0     1     5     2
#> 10  30.4     4  95.1   113  3.77  1.51  16.9     1     1     5     2
#> # … with 22 more rows
```

<sup>Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimhester** [comment]
Thanks, this is now fixed ``` r
library("magrittr")
purrr::iwalk(
 split(mtcars, mtcars$cyl), 
 ~ readr::write_tsv(.x, glue::glue("mtcars_{.y}.tsv.gz"))
)
fs::dir_ls(glob = "*tsv.gz") %>% vroom::vroom(id = "file") %>% dplyr::mutate(file = basename(file))
#> # A tibble: 32 x 12
#>    file     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <chr>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1 mtcar…  22.8     4 108      93  3.85  2.32  18.6     1     1     4     1
#>  2 mtcar…  24.4     4 147.     62  3.69  3.19  20       1     0     4     2
#>  3 mtcar…  22.8     4 141.     95  3.92  3.15  22.9     1     0     4     2
#>  4 mtcar…  32.4     4  78.7    66  4.08  2.2   19.5     1     1     4     1
#>  5 mtcar…  30.4     4  75.7    52  4.93  1.62  18.5     1     1     4     2
#>  6 mtcar…  33.9     4  71.1    65  4.22  1.84  19.9     1     1     4     1
#>  7 mtcar…  21.5     4 120.     97  3.7   2.46  20.0     1     0     3     1
#>  8 mtcar…  27.3     4  79      66  4.08  1.94  18.9     1     1     4     1
#>  9 mtcar…  26       4 120.     91  4.43  2.14  16.7     0     1     5     2
#> 10 mtcar…  30.4     4  95.1   113  3.77  1.51  16.9     1     1     5     2
#> # … with 22 more rows
```

<sup>Created on 2019-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ginolhac** [comment]
Wonderful. Thank you very much
