### ISSUE TITLE
FR: `id` argument could use names when dealing with a named vector like `map_df`

### ISSUE THREAD

**Issue by ginolhac** [jimhester/vroom#61]
Hi,

following the previous example, minus the compression, that would be super nice that the `id` argument works as the `purrr::map_df`, see for example a workflow I am using all the time:

``` r
library("magrittr")
fs::dir_create("mt")
purrr::iwalk(
 split(mtcars, mtcars$cyl), 
 ~ readr::write_tsv(.x, glue::glue("mt/mtcars_{.y}.tsv"))
)
fs::dir_ls("mt", glob = "*tsv") %>%
  purrr::set_names(nm = fs::path_file(.) %>% fs::path_ext_remove()) %>%
  purrr::map_df(readr::read_tsv, col_types = readr::cols(), .id = "file",) %>%
  dplyr::select(file:disp)
#> # A tibble: 32 x 4
#>    file       mpg   cyl  disp
#>    <chr>    <dbl> <dbl> <dbl>
#>  1 mtcars_4  22.8     4 108  
#>  2 mtcars_4  24.4     4 147. 
#>  3 mtcars_4  22.8     4 141. 
#>  4 mtcars_4  32.4     4  78.7
#>  5 mtcars_4  30.4     4  75.7
#>  6 mtcars_4  33.9     4  71.1
#>  7 mtcars_4  21.5     4 120. 
#>  8 mtcars_4  27.3     4  79  
#>  9 mtcars_4  26       4 120. 
#> 10 mtcars_4  30.4     4  95.1
#> # … with 22 more rows
  #vroom::vroom(id = "file")
```

<sup>Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

would be great to just get rid of the `map_df` and do any kind of path manipulations in the `set_names()` step.

The little neat feature of `map_df()` that could be copied is to rearrange the `id` column in first position.

Thanks again!

**Comment by jimhester** [comment]
I think it is more clear to just do the renaming after the fact. e.g.

``` r
library(dplyr)
library(fs)
library(purrr)
library(vroom)

dir_create("mt")
iwalk(
 split(mtcars, mtcars$cyl),
 ~ readr::write_tsv(.x, glue::glue("mt/mtcars_{.y}.tsv"))
)

dir_ls("mt", glob = "*tsv") %>%
  vroom(id = "file") %>%
  mutate(file = path_file(file) %>% path_ext_remove()) %>%
  select(file, mpg:disp)
#> # A tibble: 32 x 4
#>    file         mpg   cyl  disp
#>    <fs::path> <dbl> <dbl> <dbl>
#>  1 mtcars_4    24.4     4 147. 
#>  2 mtcars_4    22.8     4 141. 
#>  3 mtcars_4    32.4     4  78.7
#>  4 mtcars_4    30.4     4  75.7
#>  5 mtcars_4    33.9     4  71.1
#>  6 mtcars_4    21.5     4 120. 
#>  7 mtcars_4    27.3     4  79  
#>  8 mtcars_4    26       4 120. 
#>  9 mtcars_4    30.4     4  95.1
#> 10 mtcars_4    21.4     4 121  
#> # … with 22 more rows
```

<sup>Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

If `map_df()` always puts `.id` in the first position I will have vroom do the same.

**Comment by jimhester** [comment]
After https://github.com/jimhester/vroom/commit/304f32794d2df397a694a77dbafeb69561adfdb4 if an `id` is specified it is returned as the first column.

**Comment by ginolhac** [comment]
Fine with me I though it was more expensive to do it on all rows and not just fill in the chosen character.
