### ISSUE TITLE
All connection are in use when opening many compressed csvs

### ISSUE THREAD

**Issue by mkiang** [jimhester/vroom#64]
Not sure if this is the reason for #20, but when opening many compressed CSV files (e.g., `.csv.xz`), I get the following warning: `Error in xzfile(path, "") : all connections are in use`.

Toy example:
```
t_dir <- tempdir()
for (i in 1:1000) {
    readr::write_csv(
        tibble::tibble(
            x = rnorm(1000), 
            y = rnorm(1000)
        ), 
        sprintf("%s/%s.csv.xz", t_dir, i)
    )
}
vroom::vroom(fs::dir_ls(t_dir, glob = "*.csv.xz"))
```

**Comment by jimhester** [comment]
R has a hard max of 128 open connections, and the way the code is currently written first opens all of the connections up front. It would be possible to open them on demand, I will see what I can do about it.

**Comment by jimhester** [comment]
Thanks for the reproducible example! This now works with an arbitrary number of compressed files

``` r
t_dir <- "test"
dir.create(t_dir)
for (i in seq_len(1000)) {
    readr::write_csv(
        tibble::tibble(
            x = rnorm(1000),
            y = rnorm(1000),
        ),
      glue::glue("{t_dir}/{i}.csv.gz")
    )
}

files <- fs::dir_ls("test", glob = "*.csv.gz")
vroom::vroom(files)
#> # A tibble: 1,000,000 x 2
#>         x      y
#>     <dbl>  <dbl>
#>  1  0.923 -0.336
#>  2  0.177 -0.804
#>  3 -1.20  -0.337
#>  4  0.604  0.195
#>  5 -0.217 -0.942
#>  6 -0.383 -1.39 
#>  7  1.52  -1.39 
#>  8  0.895  0.762
#>  9  0.434 -0.111
#> 10 -1.00  -1.73 
#> # … with 999,990 more rows
```

<sup>Created on 2019-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mkiang** [comment]
Awesome. Thanks for your work on this — very cool package.
