### ISSUE TITLE
python bindings coming soon?

### ISSUE THREAD

**Issue by randomgambit** [jimhester/vroom#67]
Hi @jimhester , great job! Do you have any plans to create a python version of `vroom`? At the moment, one of the key bottleneck (at least in my setup) is exchanging information between R and Python, and `vroom` could be a very good solution here. What do you think?

Thanks!

**Comment by jimhester** [comment]
No, I have no plans to do python bindings.

If you are trying to exchange data between R and python maybe a solution would be a binary format like fst or arrow. I guess fst does not currently have python bindings, but it seems in the works https://github.com/fstpackage/fst/issues/184.

**Comment by randomgambit** [comment]
@jimhester thanks! very useful. good luck with that project!
