### ISSUE TITLE
Handling multiple CSV files with differing columns

### ISSUE THREAD

**Issue by md0u80c9** [jimhester/vroom#70]
Hi,

Not sure whether this is in-scope or not.

The zip contains two very simple CSVs - one has columns 'A, B, C' and the other columns 'A, B, D'.

I've loaded them in with:

```
files <- fs::dir_ls(path = "../Test", glob = "*csv")
df1 <- vroom::vroom(files)

```

I'd expect to see one of three possible behaviours:

1) Optimistic Merging so that there would be four rows, with NA values where a column was not supplied:

```
A, B, C, D
A, 1, 2, NA
B, 3, 4, NA
A, 1, NA, 5
B, 3, NA, 6
```

2) Pessimistic Merging so that differing columns are ignored and only the common columns retained:

```
A, B
A, 1
B, 3
A, 1
B, 3
```

3) Error that the two CSV files have different column specifications and will not be merged.

What actually happens is the output is:

```
Observations: 2                                                                                                                                                               
Variables: 3
chr [1]: A
dbl [2]: B, C


A, B, C
A, 1, 2
A, 1, 5
```

[Test.zip](https://github.com/jimhester/vroom/files/3060427/Test.zip)

**Comment by jimhester** [comment]
I am not handling this at least for the first version of vroom. It is expected that all of your files have the same columns.

**Comment by md0u80c9** [comment]
Is there value in flagging an error if any of the columns differs? I wasn't surprised that vroom couldn't handle the different files (I actually did it precisely to see what would happen): I was just rather surprised at what the output was (ie. valid-looking, but erroneous data).

**Comment by jimhester** [comment]
Thank you for opening the issue! We now check for these things and give nice error messages.

```r
# If column names differ
Error: Files must have consistent column names:
* File 1 column 1 is: A
* File 2 column 1 is: C

# If column numbers differ
Error: Files must all have 2 columns:
* File 2 has 3 columns.
```

**Comment by md0u80c9** [comment]
That's brilliant! Glad the test helped!

**Comment by hope-data-science** [comment]
I think for multiple files, it is inevitable that some csv don't have the same columns or identical column types for the current guessing mechanism. Is there a chance that we could set our expected column names and column type for the multiple files, when the current file did not fit, it returns NAs or did not read the current file but return the error reading list but still merge the valid ones?
